version: '3.8'


services:
  cache:
    image: redis:6.2-alpine
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    command:  ["--requirepass", "satyam123"]
    volumes:
      - cache:/data

  redis-commander:
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: unless-stopped
    container_name: redis-commander
    environment:
      - REDIS_HOSTS=redis
    ports:
      - "127.0.0.1:8081:8081"
    depends_on:
      - cache
  db:
    image: postgres
    container_name: db
    environment:  # Correct key for environment variables
      POSTGRES_DB: social
      POSTGRES_USER: satyam
      POSTGRES_PASSWORD: Shadowcyng@123
    volumes:
      - db-data:/var/lib/postgresql/data  # Correct volume path
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

volumes:
  db-data:
  cache: