package db

var usernames = []string{"john_doe", "jane_smith", "mike23", "sarah_lee", "chris_brown", "emma_wilson", "david_jones", "anna_taylor", "tom_harris", "kate_martin", "lisa_white", "james_clark", "amy_adams", "mark_thomas", "linda_roberts", "peter_walker", "paul_hall", "laura_green", "steve_moore", "emma_scott", "robert_king", "nancy_hill", "susan_wright", "kevin_cooper", "olivia_baker", "daniel_evans", "mary_parker", "jason_edwards", "karen_turner", "adam_morgan", "nicole_bennett", "ryan_hughes", "megan_jackson", "brandon_allen", "eric_james", "rachel_ward", "chloe_morris", "justin_howard", "alex_henderson", "lauren_patterson", "ethan_carter", "ashley_bryant", "tyler_west", "kimberly_phillips", "zachary_cole", "melissa_griffin", "victoria_richards", "joshua_bell", "molly_powell", "brian_long"}

var titles = []string{"How to Learn Programming Fast",
	"Top 10 Tips for Healthy Living",
	"Exploring the Best Travel Destinations",
	"The Ultimate Guide to Fitness",
	"Understanding Cryptocurrency Basics",
	"10 Easy Recipes for Beginners",
	"Mastering Time Management Skills",
	"A Beginner's Guide to Investing",
	"How to Stay Motivated Every Day",
	"The Science of Better Sleep",
	"Building Strong Relationships: Tips and Tricks",
	"The History of Artificial Intelligence",
	"Top Strategies for Personal Growth",
	"How to Create a Morning Routine",
	"The Best Books to Read This Year",
	"Overcoming Stress: Practical Advice",
	"Why Mindfulness Matters in Daily Life",
	"The Future of Technology and Innovation",
	"Achieving Financial Freedom: A Step-by-Step Plan",
	"The Art of Effective Communication",
}

var contents = []string{
	"Discover quick tips to accelerate your programming journey.",
	"Adopt these habits to lead a healthier and happier life.",
	"Unveil the top destinations for your next dream vacation.",
	"Learn simple yet effective ways to boost your fitness level.",
	"Understand the basics of cryptocurrency and how it works.",
	"Try these beginner-friendly recipes for delicious meals.",
	"Master time management and achieve your goals efficiently.",
	"Start your investing journey with this beginner's guide.",
	"Stay motivated daily with these proven techniques.",
	"Improve your sleep quality with these science-backed tips.",
	"Strengthen your relationships with practical advice.",
	"A deep dive into the history and growth of AI technology.",
	"Discover strategies to foster personal growth and success.",
	"Transform your mornings with this simple routine.",
	"Expand your knowledge with these must-read books.",
	"Learn to manage stress effectively in your daily life.",
	"Explore how mindfulness can improve your overall well-being.",
	"Stay ahead with insights into the future of technology.",
	"Follow this plan to achieve financial independence.",
	"Enhance your communication skills with these simple tips.",
}

var tags = []string{
	"programming", "technology", "travel", "fitness", "health",
	"cryptocurrency", "recipes", "productivity", "investing", "motivation",
	"sleep", "relationships", "artificial-intelligence", "personal-growth",
	"morning-routine", "books", "stress-management", "mindfulness",
	"financial-freedom", "communication-skills",
}

var commentsContent = []string{
	"Great post! I learned a lot from this.",
	"Thanks for sharing these insights.",
	"This is exactly what I was looking for!",
	"Can you provide more details on this topic?",
	"I completely agree with your points.",
	"This was super helpful, thank you!",
	"Do you have any book recommendations on this?",
	"I’ve been struggling with this, and this post helped a lot.",
	"Amazing tips! I’ll definitely try them out.",
	"This is a game-changer for me!",
	"I never thought about it this way. Thanks!",
	"Could you elaborate on the last point?",
	"This content is so valuable, keep it up!",
	"I appreciate the practical examples you included.",
	"Well-written and easy to follow. Thanks!",
	"I’ve bookmarked this for future reference.",
	"Any advice for beginners in this field?",
	"This is such an underrated topic. Great work!",
	"Looking forward to more posts like this!",
	"Thank you for simplifying this complex topic.",
}
